#!/usr/bin/env python3

import json
import os
import sys
import argparse
from datetime import date
from pathlib import Path

# ── Configuration ──────────────────────────────────────────────────────────────

DIFFICULTY_EMOJI = {
    "easy":   "easy",
    "medium": "medium",
    "hard":   "hard",
}

REQUIRED_FIELDS = {"title", "platform", "difficulty", "tags", "points", "date", "status"}

START_MARKER = "<!-- WRITEUPS:START -->"
END_MARKER   = "<!-- WRITEUPS:END -->"

# ── Helpers ────────────────────────────────────────────────────────────────────

def load_meta(folder: Path) -> dict | None:
    """Load and validate meta.json from a write-up folder."""
    meta_path = folder / "meta.json"
    if not meta_path.exists():
        return None

    with open(meta_path, encoding="utf-8") as f:
        try:
            meta = json.load(f)
        except json.JSONDecodeError as exc:
            print(f"Skipping {folder.name}: invalid JSON — {exc}", file=sys.stderr)
            return None

    missing = REQUIRED_FIELDS - meta.keys()
    if missing:
        print(f"Skipping {folder.name}: missing fields: {missing}", file=sys.stderr)
        return None

    return meta


def build_table(writeups: list[dict]) -> str:
    """Render the markdown table from a list of write-up metadata dicts."""
    lines = [
        f"**{len(writeups)} write-up{'s' if len(writeups) != 1 else ''}**\n",
        "| Challenge | Platform | Difficulty | Tags | Points | Date |",
        "|-----------|----------|------------|------|-------:|------|",
    ]

    for w in writeups:
        folder    = w["_folder"]
        title     = w["title"]
        platform  = w["platform"]
        diff      = DIFFICULTY_EMOJI.get(w["difficulty"].lower(), w["difficulty"])
        tags      = ", ".join(w["tags"])
        points    = w["points"]
        dt        = w["date"]

        lines.append(
            f"| [{title}](./{folder}/) | {platform} | {diff} | {tags} | {points} | {dt} |"
        )

    return "\n".join(lines)


def update_readme(readme_path: Path, table: str) -> None:
    """Replace content between START/END markers in README.md."""
    content = readme_path.read_text(encoding="utf-8")

    start_idx = content.find(START_MARKER)
    end_idx   = content.find(END_MARKER)

    if start_idx == -1 or end_idx == -1:
        print("  ✗  Markers not found in README.md.", file=sys.stderr)
        sys.exit(1)

    new_block = (
        f"{START_MARKER}\n"
        f"<!-- This table is auto-generated by .github/scripts/update_readme.py -->\n"
        f"<!-- Add a meta.json to a new folder and push — it updates automatically -->\n\n"
        f"{table}\n\n"
        f"{END_MARKER}"
    )

    new_content = content[:start_idx] + new_block + content[end_idx + len(END_MARKER):]
    readme_path.write_text(new_content, encoding="utf-8")


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate CTF write-up table in README.md")
    parser.add_argument("--readme", default="README.md",  help="Path to README.md")
    parser.add_argument("--root",   default=".",          help="Repo root to scan for write-up folders")
    args = parser.parse_args()

    root        = Path(args.root).resolve()
    readme_path = Path(args.readme).resolve()

    print(f"Scanning {root} for write-up folders…")

    writeups: list[dict] = []
    skip_dirs = {".git", ".github", "node_modules", "__pycache__"}

    for meta_path in root.rglob("meta.json"):
        folder = meta_path.parent
        rel = folder.relative_to(root)
        if any(part.startswith(".") or part in skip_dirs for part in rel.parts):
            continue

        meta = load_meta(folder)
        if meta:
            meta["_folder"] = str(rel.as_posix())
            writeups.append(meta)
            print(f"  ✓  {rel}: {meta['title']}")

    if not writeups:
        print("No write-ups found — nothing to do.")
        return

    # Sort: newest date first, then alphabetically by title
    writeups.sort(key=lambda w: w["date"], reverse=True)

    table = build_table(writeups)
    update_readme(readme_path, table)

    print(f"\n✅  README.md updated with {len(writeups)} write-up(s).")


if __name__ == "__main__":
    main()
